# Generated by Django 3.2.8 on 2021-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
